// <auto-generated />
using System;
using EFC_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFC_DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231130141553_GetAllBooksForSaleWorks")]
    partial class GetAllBooksForSaleWorks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("integer");

                    b.Property<string>("booksIsbn")
                        .HasColumnType("text");

                    b.HasKey("AuthorsId", "booksIsbn");

                    b.HasIndex("booksIsbn");

                    b.ToTable("AuthorBook", "Books");
                });

            modelBuilder.Entity("BookCourse", b =>
                {
                    b.Property<string>("BooksIsbn")
                        .HasColumnType("text");

                    b.Property<string>("coursesName")
                        .HasColumnType("text");

                    b.HasKey("BooksIsbn", "coursesName");

                    b.HasIndex("coursesName");

                    b.ToTable("BookCourse", "Books");
                });

            modelBuilder.Entity("Shared.Domain.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("authors", "Books");
                });

            modelBuilder.Entity("Shared.Domain.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasColumnType("text");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Isbn");

                    b.ToTable("books", "Books");
                });

            modelBuilder.Entity("Shared.Domain.BookForSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookIsbn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BookIsbn");

                    b.HasIndex("ConditionState");

                    b.ToTable("booksForSale", "Books");
                });

            modelBuilder.Entity("Shared.Domain.Condition", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("State");

                    b.ToTable("conditions", "Books");
                });

            modelBuilder.Entity("Shared.Domain.Course", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("courses", "Books");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Shared.Domain.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("booksIsbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookCourse", b =>
                {
                    b.HasOne("Shared.Domain.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksIsbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Course", null)
                        .WithMany()
                        .HasForeignKey("coursesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Domain.BookForSale", b =>
                {
                    b.HasOne("Shared.Domain.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookIsbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionState")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Condition");
                });
#pragma warning restore 612, 618
        }
    }
}
